# Generated by Django 6.0.6 on 2026-06-12 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacySalesFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('day', models.PositiveSmallIntegerField()),
                ('region', models.CharField(db_index=True, max_length=50)),
                ('country', models.CharField(db_index=True, max_length=100)),
                ('category', models.CharField(db_index=True, max_length=50)),
                ('medicine', models.CharField(db_index=True, max_length=100)),
                ('age_group', models.CharField(db_index=True, max_length=20)),
                ('units_sold', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=14)),
                ('stock_level', models.PositiveIntegerField()),
                ('expiry_days_remaining', models.PositiveIntegerField()),
                ('covid_flag', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etl_job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_records', to='etl.etljob')),
            ],
            options={
                'db_table': 'pharmacy_sales_fact',
                'indexes': [models.Index(fields=['region', 'country'], name='pharmacy_sa_region_b7e154_idx'), models.Index(fields=['category', 'medicine'], name='pharmacy_sa_categor_53a4df_idx'), models.Index(fields=['year', 'month'], name='pharmacy_sa_year_3b88e2_idx'), models.Index(fields=['covid_flag'], name='pharmacy_sa_covid_f_934939_idx'), models.Index(fields=['age_group'], name='pharmacy_sa_age_gro_a65596_idx'), models.Index(fields=['expiry_days_remaining'], name='pharmacy_sa_expiry__1fb75c_idx')],
            },
        ),
    ]
