# Generated by Django 6.0.6 on 2026-06-12 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pharmacysalesfact',
            constraint=models.UniqueConstraint(fields=('date', 'country', 'region', 'medicine', 'category', 'age_group'), name='unique_pharmacy_sales_fact'),
        ),
    ]
